#!/usr/bin/env node
/**
 * Seed D1 from universe/data/ files.
 *
 * Reads chains, couplings, entities, vocabulary from the universe data
 * directory and generates a SQL file that can be applied to D1 via wrangler.
 *
 * Usage:
 *   npx tsx apps/hub/scripts/seed-d1.ts                     # writes to apps/hub/seed.sql
 *   npx tsx apps/hub/scripts/seed-d1.ts --data ./universe/data --out apps/hub/seed.sql
 *
 * Then apply:
 *   cd apps/hub && wrangler d1 execute plyknot-hub --local --file=./seed.sql
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';

// ── Parse args ──────────────────────────────────────────────────────────────

let dataDir = resolve(process.cwd(), 'universe/data');
let outFile = resolve(process.cwd(), 'hub/seed.sql');

for (let i = 2; i < process.argv.length; i++) {
  if (process.argv[i] === '--data' && process.argv[i + 1]) dataDir = resolve(process.argv[++i]);
  if (process.argv[i] === '--out' && process.argv[i + 1]) outFile = resolve(process.argv[++i]);
}

// ── SQL helpers ─────────────────────────────────────────────────────────────

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

// ── Load data ───────────────────────────────────────────────────────────────

const sql: string[] = [];
sql.push('-- Auto-generated by seed-d1.ts');
sql.push(`-- Source: ${dataDir}`);
sql.push(`-- Generated: ${new Date().toISOString()}`);
sql.push('');

// Clear existing data
sql.push('DELETE FROM submissions;');
sql.push('DELETE FROM api_keys;');
sql.push('DELETE FROM users;');
sql.push('DELETE FROM embeddings;');
sql.push('DELETE FROM events;');
sql.push('DELETE FROM dependencies;');
sql.push('DELETE FROM entities;');
sql.push('DELETE FROM couplings;');
sql.push('DELETE FROM chains;');
sql.push('');

// ── Chains ──────────────────────────────────────────────────────────────────

const chainsDir = join(dataDir, 'chains');
const chainFiles = readdirSync(chainsDir).filter(f => f.endsWith('.json') && f !== 'index.json');

console.log(`Loading ${chainFiles.length} chains...`);

for (const f of chainFiles) {
  const name = basename(f, '.json');
  const raw = readFileSync(join(chainsDir, f), 'utf-8');
  const chain = JSON.parse(raw);
  const entity = chain.entity ?? name;
  const stepCount = chain.steps?.length ?? 0;
  const crackCount = (chain.steps ?? []).filter(
    (s: any) => s.convergence === 'divergent' || s.convergence === 'tension',
  ).length;

  // Re-serialize as compact JSON (no newlines) for safe SQL embedding
  const compactJson = JSON.stringify(chain);
  sql.push(
    `INSERT INTO chains (name, entity, data, step_count, crack_count) VALUES ('${esc(name)}', '${esc(entity)}', '${esc(compactJson)}', ${stepCount}, ${crackCount});`,
  );
}
sql.push('');

// ── Couplings ───────────────────────────────────────────────────────────────

const couplingsDir = join(dataDir, 'couplings');

function collectJsonlFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      files.push(...collectJsonlFiles(join(dir, entry.name)));
    } else if (entry.name.endsWith('.jsonl')) {
      files.push(join(dir, entry.name));
    }
  }
  return files;
}

const couplingFiles = collectJsonlFiles(couplingsDir);

let couplingCount = 0;
for (const filepath of couplingFiles) {
  const text = readFileSync(filepath, 'utf-8');
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const c = JSON.parse(trimmed);
    const provenance = c.provenance ? `'${esc(JSON.stringify(c.provenance))}'` : 'NULL';
    const sigma = c.sigma != null ? c.sigma : 'NULL';
    const source = c.source ?? 'measurement';
    sql.push(
      `INSERT INTO couplings (entity_a, entity_b, property, value, method, sigma, source, provenance) VALUES (${c.entityA}, ${c.entityB}, '${esc(c.property)}', ${c.value}, '${esc(c.method)}', ${sigma}, '${esc(source)}', ${provenance});`,
    );
    couplingCount++;
  }
}
console.log(`Loaded ${couplingCount} couplings.`);
sql.push('');

// ── Entities ────────────────────────────────────────────────────────────────

const entitiesFile = join(dataDir, 'entities', 'entities.jsonl');
const entityLines = readFileSync(entitiesFile, 'utf-8').split('\n').filter(l => l.trim());
console.log(`Loading ${entityLines.length} entities...`);

for (const line of entityLines) {
  const e = JSON.parse(line);
  sql.push(
    `INSERT INTO entities (id, name, tags) VALUES (${e.id}, '${esc(e.name)}', '${esc(JSON.stringify(e.tags))}');`,
  );
}
sql.push('');

// ── Dependencies ────────────────────────────────────────────────────────────

const depsFile = join(dataDir, 'vocabulary', 'dependencies.json');
const deps: any[] = JSON.parse(readFileSync(depsFile, 'utf-8'));
console.log(`Loading ${deps.length} dependencies...`);

for (const d of deps) {
  const labels = JSON.stringify(d.labels);
  const complexityLevels = JSON.stringify(d.complexityLevels);
  sql.push(
    `INSERT INTO dependencies (id, labels, description, created_by, complexity_levels) VALUES (${d.id}, '${esc(labels)}', '${esc(d.description)}', '${esc(d.createdBy)}', '${esc(complexityLevels)}');`,
  );
}
sql.push('');

// ── Events ──────────────────────────────────────────────────────────────────

const eventsDir = join(dataDir, 'events');
let eventCount = 0;
try {
  const eventFiles = readdirSync(eventsDir).filter(f => f.endsWith('.jsonl'));
  for (const f of eventFiles) {
    const text = readFileSync(join(eventsDir, f), 'utf-8');
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const e = JSON.parse(trimmed);
      sql.push(
        `INSERT INTO events (id, timestamp, type, actor, details) VALUES (${e.id}, '${esc(e.timestamp)}', '${esc(e.type)}', '${esc(e.actor)}', '${esc(JSON.stringify(e.details))}');`,
      );
      eventCount++;
    }
  }
} catch {
  // events directory may not exist yet
}
if (eventCount > 0) console.log(`Loaded ${eventCount} events.`);
sql.push('');

// ── Execute directly against local D1 SQLite ────────────────────────────────

import { execSync } from 'node:child_process';

const statements = sql.filter(s => s.trim() && !s.startsWith('--'));

// Write .sql for reference
writeFileSync(outFile, sql.join('\n'));

const isRemote = process.argv.includes('--remote');
const applyFlag = isRemote ? '--remote' : '--local';
const hubDir = resolve(outFile, '..');
// Use the database name from wrangler.toml for both local and remote
const dbName = 'plyknot-hub-prod';

console.log(`\nApplying ${statements.length} statements to D1 ${dbName} (${applyFlag})...`);

// Batch mode: write all statements to a single file and execute once.
// Remote D1 API is ~1000x faster with batch execution than per-statement.
writeFileSync(outFile, sql.join('\n'));

try {
  // Use ./seed.sql (relative to hubDir) since wrangler resolves --file relative to cwd
  const seedFileName = outFile.split('/').pop() ?? 'seed.sql';
  execSync(`cd "${hubDir}" && npx wrangler d1 execute ${dbName} ${applyFlag} --file=./${seedFileName}`, {
    stdio: 'inherit',
    timeout: 60000,
  });
  console.log(`\nDone: ${statements.length} statements applied.`);
} catch (e) {
  console.error(`\nBatch execution failed: ${(e as Error).message?.split('\n')[0]}`);
  process.exit(1);
}
