/**
 * GitHub PR creation — shared logic for all write endpoints.
 *
 * Pattern: read file from main → modify → create branch → commit → open PR.
 * Uses the GitHub REST API via GITHUB_TOKEN.
 */

export interface PrResult {
  prNumber: number;
  prUrl: string;
  branch: string;
}

export interface GitHubEnv {
  GITHUB_TOKEN: string;
  GITHUB_OWNER: string;
  GITHUB_REPO: string;
}

interface FileUpdate {
  path: string;
  content: string;
  message: string;
}

const API = 'https://api.github.com';

function headers(token: string) {
  return {
    authorization: `Bearer ${token}`,
    accept: 'application/vnd.github+json',
    'content-type': 'application/json',
    'user-agent': 'plyknot-hub/0.1.0',
    'x-github-api-version': '2022-11-28',
  };
}

async function ghFetch(token: string, path: string, init?: RequestInit) {
  const resp = await fetch(`${API}${path}`, { ...init, headers: headers(token) });
  if (!resp.ok) {
    const body = await resp.text();
    throw new Error(`GitHub API ${resp.status}: ${body.slice(0, 200)}`);
  }
  return resp.json() as Promise<any>;
}

/**
 * Get the SHA of a file on a given branch (or null if it doesn't exist).
 */
async function getFileSha(env: GitHubEnv, filePath: string, ref = 'main'): Promise<string | null> {
  try {
    const data = await ghFetch(
      env.GITHUB_TOKEN,
      `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${filePath}?ref=${ref}`,
    );
    return data.sha ?? null;
  } catch {
    return null;
  }
}

/**
 * Read a file's content from the repo (base64 decoded).
 */
export async function readFile(env: GitHubEnv, filePath: string, ref = 'main'): Promise<string | null> {
  try {
    const data = await ghFetch(
      env.GITHUB_TOKEN,
      `/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${filePath}?ref=${ref}`,
    );
    if (data.content) {
      return atob(data.content.replace(/\n/g, ''));
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Create a branch, commit file changes, and open a PR.
 */
export async function createPullRequest(
  env: GitHubEnv,
  opts: {
    branch: string;
    title: string;
    body: string;
    files: FileUpdate[];
  },
): Promise<PrResult> {
  const { branch, title, body, files } = opts;
  const repo = `${env.GITHUB_OWNER}/${env.GITHUB_REPO}`;

  // 1. Get main branch SHA
  const mainRef = await ghFetch(env.GITHUB_TOKEN, `/repos/${repo}/git/ref/heads/main`);
  const baseSha = mainRef.object.sha;

  // 2. Create branch
  await ghFetch(env.GITHUB_TOKEN, `/repos/${repo}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  });

  // 3. Commit each file to the branch
  for (const file of files) {
    const existingSha = await getFileSha(env, file.path, branch);
    await ghFetch(env.GITHUB_TOKEN, `/repos/${repo}/contents/${file.path}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: file.message,
        content: btoa(unescape(encodeURIComponent(file.content))),
        branch,
        ...(existingSha ? { sha: existingSha } : {}),
      }),
    });
  }

  // 4. Open PR
  const pr = await ghFetch(env.GITHUB_TOKEN, `/repos/${repo}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title,
      head: branch,
      base: 'main',
      body,
    }),
  });

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
    branch,
  };
}

/**
 * Build a standard PR body with machine-readable block + human summary.
 */
export function buildPrBody(opts: {
  type: string;
  actor: string;
  payload: unknown;
  validation: string[];
}): string {
  const { type, actor, payload, validation } = opts;
  const validationBlock = validation.length
    ? validation.map((v) => `- ${v}`).join('\n')
    : '- All checks passed';

  return `## ${type}

Submitted by \`${actor}\` via Hub API.

### Validation
${validationBlock}

### Payload
\`\`\`json
${JSON.stringify(payload, null, 2)}
\`\`\`

---
🤖 Generated by [plyknot-hub](https://hub.plyknot.org)`;
}
