/**
 * Loader for the internal R&D universe data.
 * Reads from the static JSON file generated by scripts/seed-internal-universe.py.
 * Agents in the repo can read this file directly at this path.
 */
import type { HubStats, HeatmapResponse, ChainsResponse, CracksResponse } from "../../../lib/hub-api";
import universeData from "./internal-universe.json";

export interface InternalStep {
  claim: string;
  level: string;
  complexity: number;
  convergence: string;
  sigma: number;
  depends: string[];
}

export interface InternalChain {
  entity: string;
  steps: InternalStep[];
}

const data = universeData as {
  stats: HubStats;
  heatmap: HeatmapResponse;
  chains: ChainsResponse;
  cracks: CracksResponse;
  inference_chains: InternalChain[];
};

export function fetchInternalStats(): Promise<HubStats> {
  return Promise.resolve(data.stats);
}

export function fetchInternalHeatmap(): Promise<HeatmapResponse> {
  return Promise.resolve(data.heatmap);
}

export function fetchInternalChains(): Promise<ChainsResponse> {
  return Promise.resolve(data.chains);
}

export function fetchInternalCracks(): Promise<CracksResponse> {
  return Promise.resolve(data.cracks);
}

/** Full inference chain detail for drill-down views. */
export function getInternalChain(entityName: string): InternalChain | undefined {
  return data.inference_chains.find((c) => c.entity === entityName);
}

export function getAllInternalChains(): InternalChain[] {
  return data.inference_chains;
}
